### ISSUE TITLE
Виправити все

### ISSUE THREAD

**Issue by volodymyr-kushnir** [LefkaLefka/BSA_HW_1#1]
Назва статті (наприклад, тої що про Angular) містить `-` на початку рядка і тому форматується як список. Можливо варто видалити `-`.

**Comment by LefkaLefka** [comment]
Так, згоден, підправив.

**Comment by volodymyr-kushnir** [comment]
@LefkaLefka зачекай-но, тебе ж я ще не оцінив, вірно?

**Comment by LefkaLefka** [comment]
Оцінили, тільки я щось не зрозумів одни момент: "Все начебто добре, але ані гілок, ані пул-реквестів немає." З пулом я згоджуюся, бо я не бачив логіки навіщо його використовувати, а про гілки то вони є: в одній я редагував коментарі, а в іншій саму статтю, потім "з'єднав" їх в masters

**Comment by volodymyr-kushnir** [comment]
@LefkaLefka а, то був не я. Я лишав на потім, бо в тебе граф виглядав унило https://github.com/LefkaLefka/BSA_HW_1/network
А шо там за оцінка стоїть?

**Comment by LefkaLefka** [comment]
6/10

**Comment by volodymyr-kushnir** [comment]
@LefkaLefka готовий допрацювати шоб більше (я поясню всі пред'яви) чи влаштовує?

**Comment by LefkaLefka** [comment]
готовий, бо не зовсім зрозуміло було тексту дз.

**Comment by volodymyr-kushnir** [comment]
@LefkaLefka ну, якшо зробити текст явним, то в всіх всьо однакове буде. Отже, за роботу з git-ом максимум 8 балів, 1 екстра-бал за статті (маркдаун, зручність читання), 1 екстра-бал за еджайл (проект і вот ето вот всьо). Хороший репозиторій (вот наприклад, нормальний — https://github.com/volodymyr-kushnir/agenda/) має опис, має теги, має README.md, має посилання на статті в тому README.md. Тепер, раз це проект (а це [**проект**](https://github.com/volodymyr-kushnir/agenda/projects)), то проект має назву і має завдання, до яких потім створюються ішшюс, які потім закриваються. В такий спосіб видно всю історію розробки. Вот, читай лайфхаки (ми їх не анонсували) і виправляй шо вважаєш за потрібне виправити. Крикни мені на @volodymyr-kushnir, якшо є питання. За годину мав би встигнути. І да, починай з проекту, склади вперед план роботи.

**Comment by volodymyr-kushnir** [comment]
@LefkaLefka і ше виклади мені результат `git reflog` скріншотом і `git log --graph --decorate --oneline`

**Comment by LefkaLefka** [comment]
@volodymyr-kushnir зрозумів, що деякі фічі раніше не юзав, дякую, що "наткнули")

а так то наче виправив
![image](https://cloud.githubusercontent.com/assets/21996921/26373240/6d6323f2-4009-11e7-905f-3b7cb38b8d3e.png)

**Comment by volodymyr-kushnir** [comment]
@LefkaLefka чекай-чекай. Pull Request мій прийми.

**Comment by LefkaLefka** [comment]
@volodymyr-kushnir готово)

**Comment by volodymyr-kushnir** [comment]
Тааааакс, тепер, про те, шо GitHub автоматично робить лінки на комміти і ішшю ти напевно в курсі (наприклад, #6 або c19d62893f7b0bcaf2925db0ee8b1828ec0596b5)

**Comment by LefkaLefka** [comment]
так, в курсі

**Comment by volodymyr-kushnir** [comment]
@LefkaLefka супер, отже я тобі зараз відкрию ішшю, а ти порішаєш проблему, що там описана, а потім коммітнеш з меседжом яким захочеш, але ще допишеш (fixes #<номер-який-я-відкрию>).

**Comment by volodymyr-kushnir** [comment]
@LefkaLefka окєй, ми в порядку (майже, бо ішшю не мають лейблів і Assignee). Ну і це все треба було робити вперед, а не заднім числом. Суть в тому шо кльовий репозиторій має мати приємний і понятний **README.md** (вот ти шукаєш бібліотеку для _х_ — дуже ти вчитуєшся в код, якшо нема **README.md**?), репо-мейнтейнер має приймати правки від іншого учасника (коммюніті як не як), як і слідкувати за тим, шоб його ішшю були нормально організовані і зрозумілі. Вміти круто коммітити — то тільки 80% роботи, ось моя думка.

Отже, по чесноку я мав би зараз попросити того, хто оцінював, переоцінити ще раз, але то вже пізно і тому я краще сам. Я вважаю 9. Ти як вважаєш?

**Comment by LefkaLefka** [comment]
@volodymyr-kushnir погоджуюся, код ще півділа (не зовсім, але близько), бо без нормальної документації ніхто не захоче читати код, хіба дуже треба буде. Так, так, згоден.

**Comment by volodymyr-kushnir** [comment]
@LefkaLefka продано, 9.
